#### 1. Import the numpy package

In [1]:
import numpy as np

#### 2. Create a 1-dimensional NumPy array with size of 10 filled with value 0

In [2]:
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 3. Create a 1-dimensional NumPy array with size of 10 filled with value 1

In [3]:
np.ones(10, dtype=int)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 4. Create a 1-dimensional NumPy array with size of 10 filled with value 3.14

In [4]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

#### 5. Create a 2-dimensional NumPy array with shape (5,5) filled with value 3.14

In [5]:
x1 = np.full((5,5), 3.14)
x1

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### 6. Calculate the total bytes used by the array in #5

In [6]:
print("Total Bytes: ", x1.nbytes)

Total Bytes:  200


#### 7. Create a NumPy array with values in range from 21 to 100

In [7]:
x = np.arange(21, 101)
x

array([ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
        34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
        47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100])

#### 8. Reverse the array in #7

In [8]:
x[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21])

#### 9. Create a 10x10 identity matrix

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 10. Create a 20x20 NumPy array with random values and find the minimum and maximum values

In [10]:

x3 = np.random.random(size=(20, 20))
x3

array([[2.25384986e-01, 2.03856972e-02, 1.83592990e-01, 3.04487436e-01,
        4.70272181e-01, 5.04669039e-01, 5.47483316e-03, 7.43709890e-01,
        7.80368020e-03, 1.43376987e-01, 6.63317184e-01, 8.34327365e-03,
        3.91701657e-01, 2.70530554e-01, 7.79263088e-01, 9.48645344e-01,
        1.98039812e-01, 9.94666829e-01, 6.45323429e-01, 6.45680193e-01],
       [8.42413952e-01, 2.29488404e-01, 4.74278657e-01, 6.28529685e-01,
        8.03191016e-01, 8.42797950e-01, 1.79076769e-01, 3.84064538e-01,
        6.76093320e-01, 1.92780192e-02, 2.79923713e-01, 4.61427416e-01,
        6.44565489e-01, 1.79629616e-02, 5.45765418e-02, 6.55397394e-01,
        4.04804360e-01, 4.50205122e-02, 4.56848544e-04, 6.24075745e-01],
       [7.58817271e-01, 8.63080765e-01, 2.29855667e-02, 2.48921937e-01,
        4.11665682e-01, 3.54590779e-01, 6.76170120e-01, 6.96855580e-01,
        7.80827506e-01, 8.53033417e-01, 3.10450069e-01, 4.34784403e-01,
        3.86857588e-01, 8.23513578e-01, 1.08354058e-01, 3.7241

In [11]:
x3.min()

0.0004568485444331749

In [12]:
x3.max()

0.9946668293116547

#### 11. Create a 6x6 NumPy array with random values. Split the array evenly vertically

In [13]:
np.random.seed(0)
x4 = np.random.randint(10, size=(6,6))
x4


array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3]])

In [14]:
upper, lower = np.vsplit(x4, 2)
print("Upper: ")
print(upper)
print("Lower: ")
print(lower)

Upper: 
[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]]
Lower: 
[[8 1 5 9 8 9]
 [4 3 0 3 5 0]
 [2 3 8 1 3 3]]


#### 12. For the same arry in #11, split the array evenly horizontally

In [15]:
left, right = np.hsplit(x4, 2)
print("Left: ")
print (left)
print("Right: ")
print(right)

Left: 
[[5 0 3]
 [3 5 2]
 [8 8 1]
 [8 1 5]
 [4 3 0]
 [2 3 8]]
Right: 
[[3 7 9]
 [4 7 6]
 [6 7 7]
 [9 8 9]
 [3 5 0]
 [1 3 3]]
