In [16]:
import numpy as np
import random
from datetime import date
import datetime
from datetime import datetime

1. Create a sample code of partitioning. Use 5 as k argumemnt.

In [17]:
g = np.arange(0, 10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.partition(g, 5)

array([1, 0, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
y = np.random.randint(0, 10, (1, 10))
y

array([[3, 3, 9, 8, 4, 2, 7, 2, 8, 6]])

In [20]:
np.partition(y, 5)

array([[3, 3, 2, 2, 4, 6, 7, 8, 8, 9]])

2. Create a sample structure array using following specification:
- name: OrderDate, format: unicode maximum 8 characters
- name: OrderAmount, format: float 8-bytes
- name: OrderNumber, format: integer 4-bytes
- name: OrderName, format: unicode maximum 20 characters

In [21]:
data = np.zeros(10, dtype ={'names': ('OrderDate', 'OrderAmount', 'OrderNumber', 'OrderName'),
                          'formats' : ((np.str_,8), (np.float64), int, (np.str_, 20))})
print(data.dtype)

[('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')]


In [22]:
OrderAmount =[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
OrderName = ['Angel', 'Boy', 'Colt', 'Dough', 'Eun', 'Fay', 'Gail', 'Hope', 'Indie', 'Jay']
OrderAmount = [1.23, 4.56, 7.89, 10.11, 12.13, 14.15, 16.17, 18.19, 19.20, 21.22]

In [23]:
# Odates is a list of 10 order dates start from 1-1-2020, stop 1-31-2020, every 3 days
Odates = np.arange(date(2020, 1, 1), date(2020, 1, 31), 3)
print(Odates)

['2020-01-01' '2020-01-04' '2020-01-07' '2020-01-10' '2020-01-13'
 '2020-01-16' '2020-01-19' '2020-01-22' '2020-01-25' '2020-01-28']


In [24]:
# Change the Unicode 10 to Unicode 8
OrderDate = []
for i in Odates:
    i_type = i.astype(datetime)
    i_strf = i_type.strftime("%x")
    OrderDate.append(i_strf)

print(OrderDate)

['01/01/20', '01/04/20', '01/07/20', '01/10/20', '01/13/20', '01/16/20', '01/19/20', '01/22/20', '01/25/20', '01/28/20']


3. Using #2, create a NumPy array of 10 elements with proper initialization of the structured array. Note order numbers must be between 101 - 110.

In [25]:
OrderNumber = np.arange(101, 111)
OrderNumber

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [26]:
data['OrderAmount']= OrderAmount
data['OrderNumber']= OrderNumber
data['OrderName']= OrderName
data['OrderDate']= OrderDate

4. Using the array in #3, filter the array to return orders with order number less than 105. 

In [27]:
data[data['OrderNumber']< 105]  

array([('01/01/20',  1.23, 101, 'Angel'), ('01/04/20',  4.56, 102, 'Boy'),
       ('01/07/20',  7.89, 103, 'Colt'),
       ('01/10/20', 10.11, 104, 'Dough')],
      dtype=[('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')])

5. Using the code snippet below, fill-in the cell to generate the array as shown at the bottom. 
- You will need to use fancy indexing and masking. 
- Select rows with indices 0, 3, 4, 6, 7
- Use column masking to return every other columns. The first column will be returned, 2nd column will not and so on. 

In [28]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(10, 10))

In [29]:
x

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [30]:
row = np.array([0, 3, 4, 6, 7])
mask = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=bool)
x[row[:,np.newaxis], mask]


array([[5, 3, 7, 3, 2],
       [2, 8, 3, 3, 0],
       [9, 0, 7, 2, 2],
       [8, 1, 9, 3, 7],
       [0, 5, 4, 6, 4]])